#!/bin/bash
# Quick Start Script for TotalWine Clone

echo "🍷 TotalWine Clone - Quick Start"
echo "================================"
echo ""
echo "Choose how to run the project:"
echo ""
echo "Option 1: Python HTTP Server"
echo "  python -m http.server 8000"
echo "  Then visit: http://localhost:8000"
echo ""
echo "Option 2: Node.js HTTP Server"
echo "  npx http-server"
echo "  Then visit the shown URL"
echo ""
echo "Option 3: VS Code Live Server"
echo "  - Install 'Live Server' extension"
echo "  - Right-click index.html"
echo "  - Select 'Open with Live Server'"
echo ""
echo "Option 4: Direct Browser"
echo "  - Simply open index.html in your browser"
echo "  - (Some features may not work due to CORS)"
echo ""
echo "After opening, you should see:"
echo "  ✓ Navigation header with cart"
echo "  ✓ Carousel with 3 promotional slides"
echo "  ✓ Category cards (Wine, Beer, Spirits, etc.)"
echo "  ✓ 8 featured products"
echo "  ✓ Newsletter subscription"
echo "  ✓ Footer with links"
echo ""
echo "💡 Tips:"
echo "  - Check console (F12) for initialization messages"
echo "  - Click 'Add to Cart' to test functionality"
echo "  - Test on mobile by resizing browser window"
echo ""
echo "📚 Documentation:"
echo "  - README.md - Quick overview"
echo "  - DEPLOYMENT.md - Full setup & customization"
echo "  - API_INTEGRATION.md - Connect to real API"
echo "  - TESTING.md - Testing checklist"
echo "  - PROJECT_SUMMARY.md - Complete summary"
echo ""
